# Generated by Django 3.0 on 2024-02-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_SONG', models.IntegerField()),
                ('SONG_NAME', models.CharField(max_length=100)),
                ('SONG_PATH', models.CharField(max_length=100)),
                ('PLAYS', models.IntegerField()),
            ],
        ),
    ]
